feat: add notification app(WIP)
OpenUnited/product-factory-backend pull request #136
Opened 2022-02-23 20:23 UTC by mnunzio

- installed and configured celery in Django
- add a new app notification to contain tasks and models to manage various type of notification
- add task notification call when a user claim a task

2022-03-16 08:56 UTC, ashikzk requested changes

2022-03-16 08:56 UTC, ashikzk commented on notification/models.py
> +
There should be another set of `TYPES` defined in this notification app. That type will define what type of method the notification should be sent: Email OR SMS. The notification type mentioned in the original architectural diagram actually meant that. Please add them too as `NOTIFICATION_TYPE_EMAIL` and `NOTIFICATION_TYPE_SMS`. For now, we will only be using email type.

2022-03-16 08:56 UTC, ashikzk commented on notification/tasks.py
> +def send_notification(notification_type, **kwargs):
`send_notfication` should take two type params: one to define how to send the notification (email or sms) and another to define the message_type (TASK_CLAIMED, TASK_CLAIM_COMMENT, SUBMISSION_APPROVED, etc.). Currently all notification is being sent to send_email which is incorrect.

2022-03-20 18:25 UTC, nsavch commented on notification/models.py
> +
I think it would be better to use enums for listing notification types.  Django supports enums for choices since 3.0: https://docs.djangoproject.com/en/dev/releases/3.0/#enumerations-for-model-field-choices

2022-03-31 13:11 UTC, ashikzk commented on notification/models.py
> +        TASK_CLAIM_REQUEST_APPROVED = 19, _('Task Claim Request Approved')
`TASK_CLAIM_REQUEST` cannot be cancelled, rejected or approved. A contributor can claim a task directly without any approval. So, choices 17,18, 19 should be removed.

2022-03-31 14:07 UTC, ashikzk reviewed
Everything is looking good. Please make the requested few minor changes and it should be good to be merged.

2022-03-31 14:07 UTC, ashikzk commented on notification/migrations/0001_initial.py
> +    ]
Please add the new migration. I think you forgot to add that after the choice update.

2022-04-02 09:12 UTC, mnunzio commented on notification/migrations/0001_initial.py
> +    ]
I actually went to replace the old migration rather than generate a new one. This given that it was still a provisional structure and I did not think it was already integrated but if you want I can easily generate it, let me know.

2022-04-02 09:14 UTC, mnunzio commented on notification/models.py
> +        TASK_CLAIM_REQUEST_APPROVED = 19, _('Task Claim Request Approved')
I had added them according to the cases presented [here](https://github.com/OpenUnited/product-factory-backend/pull/136/files#diff-f92e3dd0cfaccc26ae0d39142a8e9819319c8e401997118a182c1315cb304970), should the receiver save_task_claim also be deleted? or simply sending emails?

2022-04-02 09:30 UTC, mnunzio commented on notification/models.py
> +        TASK_QUITTED = 14, _('Task Quitted')
I don't think it should be deleted rather renamed because in the code the cases in which these emails are sent is different. In the first case (TASK_QUITTED) the task claim has been set in a failed state while the second (CONTRIBUTOR_LEFT_TASK) case concerns a canceled task delivery attempt. What do you think?

2022-04-04 18:23 UTC, ashikzk commented on notification/models.py
> +        TASK_CLAIM_REQUEST_APPROVED = 19, _('Task Claim Request Approved')
Yes, I agree with you. I cannot think of a flow where a task claim request can be cancelled or rejected. A task claim object can only be in one of four states: `Active`, `In Review`, `Done` and `Failed`. I believe we can safely remove old unnecessary notifications state changes that we feel are no longer needed.

2022-04-04 18:37 UTC, ashikzk commented on notification/migrations/0001_initial.py
> +    ]
Replacing the original migration is fine. Since we haven't merged it yet, that is in fact ideal. However, what I noticed is that the migration file does not contain all the states that you added recently. It still contains 5 states. Can you please re-check to confirm? Thanks.

2022-04-17 14:03 UTC, merged