task 87 depend on blocked tasks
OpenUnited/product-factory-backend pull request #145
Opened 2022-05-12 00:54 UTC by gasparRemoteWork

Allow selecting a blocked task as a dependency of another task

**WARNING**: We modified get_current_person so it checks first the fake login user id. It makes sense to us that FAKE_LOGIN_USER_ID has priority over the other ids, also it was a **NECESSARY CHANGE** to make it work in the local environment

2022-05-16 10:57 UTC, ashikzk requested changes

2022-05-16 10:57 UTC, ashikzk commented on work/models.py
> -
Why was this removed? When "available" task filter is being used, we do want to see only the available tasks, not the blocked ones. Please let me know why this was removed.

2022-05-17 02:32 UTC, gasparRemoteWork commented on work/models.py
> -
I think I misunderstand the purpose of this filter. How is it supposed to work? I mean, the var statuses is an array so it can have multiple statuses. And the filter (line 526) is using a **__in** operator, so I think that the idea is that we can use it to retrieve tasks of different statuses in one call. But, If we don't allow tasks to have active dependencies when "available" is one of the statuses to retrieve, we can't retrieve tasks of status "available" and "blocked" at the time.

My suggestion is to modify the line 528 to also check if "available" is also the only status in the statuses array:
   `if Task.TASK_STATUS_AVAILABLE in statuses and len(statuses) == 1:`

or maybe check that "blocked" status is not present:
`if Task.TASK_STATUS_AVAILABLE in statuses and Task.TASK_STATUS_BLOCKED not in statuses:`

please check this answers I leave in the front PR to get more context: 
[https://github.com/OpenUnited/product-factory-frontend/pull/191#discussion_r874295334](https://github.com/OpenUnited/product-factory-frontend/pull/191#discussion_r874295334)
[https://github.com/OpenUnited/product-factory-frontend/pull/191#discussion_r874296206](https://github.com/OpenUnited/product-factory-frontend/pull/191#discussion_r874296206)

2022-05-17 11:01 UTC, ashikzk commented on work/models.py
> -
I agree with you. We do need to be able to retrieve both available and blocked tasks using the same filter. It is not possible with the current implementation. I like your seconds option i.e. check "blocked" status not present when "available" is present. Please make that modification and push the updates.

2022-05-19 10:45 UTC, ashikzk approved these changes

2022-05-19 10:48 UTC, ashikzk commented on api/talent/schema.py
> +
Why was this added?

2022-05-19 10:49 UTC, ashikzk requested changes
@gasparRemoteWork The PR needs to be made against staging. I can see two additional changes being shown when I changed the based to staging. Please reply to the new clarifications. Thanks.

2022-05-19 10:49 UTC, ashikzk commented on api/work/mutations.py
> +    def mutate(current_person, info, *args, **kwargs):
Please explain why this was added.

2022-05-20 01:32 UTC, gasparRemoteWork commented on api/talent/schema.py
> +
Not mine, I think this appear when the target branch change from master to staging. I rebase my branch. This should solve the issue

2022-05-20 01:33 UTC, gasparRemoteWork commented on api/work/mutations.py
> +    def mutate(current_person, info, *args, **kwargs):
Not mine. I think this appeared when the target branch was changed from master to staging. I rebased my branch. The issue should be resolved

2022-06-02 15:25 UTC, ashikzk approved these changes

2022-06-02 15:26 UTC, merged